### ISSUE TITLE
Should Readium-2 development be cross-platform or per-platform

### ISSUE THREAD

**Issue by rkwright** [readium/readium-2#2]
#### This is a Discussion

Should the goal be to be as cross-platform as possible or give up on that and write platform-specific implementations? E.g. Objective C/Swift on iOS, Java on Android, etc.

**Comment by rkwright** [comment]
From Jean-Marie:
DRMs are currently plugged as ContentFilters and are very independent from the rest of the SDK, this is why I suggested to limit the native code to it. My suggestion simply aims at allowing developers of "basic" apps to rely on simple build and debug toolkits. On Android, mixing Java and C++ is a pain (it's easier now thx to the latest Android Studio tools but still complex). Hence my suggestion to limit the need to use C++ to the integration of DRMs. Even for these DRMs, most of them (Adobe and URMS) are now distributed as prebuilt libs.

**Comment by rkwright** [comment]
From Yuri Khramov:
 As you might know, we used the specific bridges for Readium JS on every platform. However, Readium SDK got some traction, and I would expect even more after SONY’s release of the DRM specifically tailored for Readium SDK. So, I vote for continuing with the cross-platform code for the SDK.

**Comment by rkwright** [comment]
From Jean-Marie:
DRMs are currently plugged as ContentFilters and are very independent from the rest of the SDK, this is why I suggested to limit the native code to it. My suggestion simply aims at allowing developers of "basic" apps to rely on simple build and debug toolkits. On Android, mixing Java and C++ is a pain (it's easier now thx to the latest Android Studio tools but still complex). Hence my suggestion to limit the need to use C++ to the integration of DRMs. Even for these DRMs, most of them (Adobe and URMS) are now distributed as prebuilt libs.

**Comment by rkwright** [comment]
My concern about platform-specific implementations is that we will end up with multiple code-bases, possibly **4**

- iOS (Objective C/Swift)
- Android (Java)
- Desktop (Hybrid of some form)
- CloudReader (JavaScript)

The development would be bad enough, but the scope of testing could be scary.  In addition, the pattern has not been that people work on the code evenly across platforms, so the codebases would drift apart.

**Comment by HadrienGardeur** [comment]
I think that the debate between platform specific or cross-platform doesn't matter as much as defining how we'll interact with Core SDK or its equivalent.

If we define a simple API for that, then anyone could implement what they want.

**Comment by rkwright** [comment]
Of course, that's the beauty of interfaces, but as Readium we have to implement support on several platforms, so the question is which ones and what is that implementation.  
When you say the "Core SDK" are you implying that you favor there being one central core as there is today, in C++?

**Comment by HadrienGardeur** [comment]
No I'm not necessarily in favour of a central core.

Right now in 1.0, it feels that there are too many interactions required, for very little info in return.

My own proposal regarding that is to treat the equivalent of the Core SDK like a server from which I can request a manifest, and in return I get a manifest with everything I'll ever need: link to all the resources, metadata, ToC etc.

One GET request, and then I'm done, from now on I just request various resources.

**Comment by rkwright** [comment]
Right.  I like the concept.  Several people have pointed that the Core doesn't really DO a lot that the browsers can do (and often better).

**Comment by llemeurfr** [comment]
My take would be to keep C++ for DRM client modules (Readium LCP and Sony URMS), maybe also for EPUB parsing (and optimized access to the zipped content), JS for anything interacting with the browser engine, and have clearly defined interfaces for the the "middleware", with portable JS modules (as a reference) which can be replaced by native modules when performance is key.

**Comment by rkwright** [comment]
## Proposed Solution
In the [Readium-2 meeting on October 5](https://docs.google.com/document/d/14Cbsr1cmZRvREUoxEs3OjxPERH_3JmkxkIN94huSrEQ/edit#), the group came to a general consensus that the development should be largely but not entirely per-platform.  It is expected that there may be some code (e.g. JavaScript managing the browser instance) might be shared but this would be limited at best. In addition, the DRM implementations (i.e. LCP, Sony) would be in C++ with a glue layer to the Core.

This consensus was based on the tentative implementation strategy of

|Platform | Strategy |
|---------|----------|
|iOS         | Objective-C and/or Swift |
|Android | Java |
|Windows | Electron Hybrid wrapping JavaScript with hooks to native/OS|
|OSX | Electron Hybrid wrapping JavaScript with hooks to native/OS|
|Linux | Electron Hybrid wrapping JavaScript with hooks to native/OS|
|CloudReader | JavaScript |

The reasons for proposing this strategy includes:

1. The writing the code three times would be more than offset by the difficulty of writing all the glue code layers (JNI, RDServices) then maintaining those layers. The exception to this would be the need for a JNI layer for the DRM functionality.
2. Writing the code in platform-specific languages makes it much easier to leverage platform-specific functionality, which in turn makes it easier to create performant applications with a good user experience and proper accessibility.
3. Having different implementations on each platform is much more likely to attract new contributors since they can work in an environment and language they are familiar with and enjoy.

Alternatively, it was pointed out that there were several downsides:

1. Having to implement the code three times
2. Having to test on multiple platforms, but that has to happen to happen in any case.  But the bugs almost certainly will be different across platforms.
3. The strategy pretty much guarantees that Readium-2 is a re-write, not a refactoring.  The basic algorithms can, in some cases, be re-used but little or no code will be able to be re-used except in  a limited way for the JavaScript stack.  However, even there the use of Promise/Future and strict API contracts would mean that vast majority of the code will touched anyway.
4.  We can get rid of the @#$! sub-modules

It should be pointed out that one aspect of Readium that SHOULD be as cross-platform as possible is the set of interfaces which exposes R2's functionality to the reading system.  These interfaces have to be very carefully spec'ed out and then strictly enforced. This serves at least two purposes:

1. It minimizes the drift of functionality between the platforms.  The underlying implementations can and will be somewhat different, but we should endeavour to keep them as much alike as possible.
2. It makes writing reading systems for the different supported platforms much easier  since the APIs will be very similar, minimizing the learning curve.
