### ISSUE TITLE
Using an agile approach to design and prototype the architecture for Readium-2

### ISSUE THREAD

**Issue by rkwright** [readium/readium-2#20]
In the Readium-2 engineering meeting on 9 November, the team discussed two big issues:

- how to get to an actual architectural design for Readium-2
- what approach should be used to get there

Previously, the contributors had agreed (at the behest of the Readium board) to generate three deliverables in Phase 1 of the Readum 2 project 

- A design for the the architecture of Radium-2
- A set of interfaces that app-developers could design to
- An estimate of the scope/manpower/timeframes for reaching a viable Readium-2

 where Phase 1 was to be completed in the November/December 2016 timeframe.  As part of that process, the group reached a consensus that

- Readium-2 would focus on the mobile solution strategy, i.e. iOS and Android and leave JavaScript-based solutions like the Chrome Extension and the Cloud Reader for later
- that development on those platforms would be largely (if not completely) per-platform, i.e. the implementation would be based on native tools and code

However, one of the implications of this approach was that R2 would effectively be a complete rewrite of the existing codebase.  Several members of the group were uncomfortable with this approach (see email thread here).

In the discussion on 9 November, however, the group came to the conclusion that trying to develop the code in an incremental fashion by developing pieces of Readium-2 separately then integrating them into a fork of Radium-1 was most likely an unworkable solution.  The ripple of effect of changing  APIs and the behavior of code modules would make that very difficult.

The group came to the conclusion that a more viable solution would be
To start with the most fundamental piece of an EPUB reading system, the parser

- Write the interface(s) for the parser using TypeScript (for the typing ability)
- Prototype this interface and design in TypeScript
- Develop tests along with this code to ensure that it all works as designed

When the parser would be complete, move onto the next step (e.g. the model representing the parsed EPUB) and so on.  Eventually, the completed and tested code would/could be “ported” to native languages and libraries for iOS and Android.  The TypeScript (transpiled to JavaScript) could be used as a replacement for the ReadiumJS stack as well.

Arguably, this represents a move from the original “waterfall-like” design/implementation approach to a more agile approach.  

Pros:
This allows the development to be done bottom-up in a more natural design process
There is little or no integration pain since the development is bottom up
The resulting code is cleanly developed (with typing) and associated tests
Cons:
The time from beginning to the process will very likely be much longer to reach native-code implementation since the TypeScript version must be developed first
Since the development would be agile, providing a scope and timeframe is infeasible, as is concrete interfaces win a specified timeframe
?

**Comment by HadrienGardeur** [comment]
I agree that starting from the parser is a good idea, but I wouldn't stop there: I think we should build both the parser and the HTTP serveur hands in hands together.

That said, there's something that I feel like I'm missing here: wouldn't the parser be written per platform and in a native language? Why are we talking about using TypeScript for that part of the code? If mobile is our priority, this makes IMO a lot more sense than doing TypeScript first.

**Comment by HadrienGardeur** [comment]
The whole Typescript-then-native thing sounds half-agile to me.

I believe we should start with a very basic MVP for iOS (Swift?) and Android (Java) and iterate from there. For these MVP, pagination can be handled by injecting a super basic JS in HTML resources, which means that other from a webview, we don't really need anything else to test the parser/server.

We can then easily iterate from there by improving the parser/server, fully testing etc. We might even see other projects interested (like FolioReader) and integrate our parser/server.

**Comment by llemeurfr** [comment]
Using Typescript for modeling the Parser interface has three concret advantages
- it is an alternative to the large set of IDL languages that nobody will agree about
- it is a way to test Typescript, which is viewed by the group as an interesting solution for the JS part.
- it is a way to avoid having to choose btw Java, Objective -C and Swift  for such a reference development. Some in the groupe have XCode, others have Android studio, everybody can manipulate JS code. 

But as soon as we have agreed on the interface definition, it will be good to have iOS/Android implementations of this parser. 

I note one issue with a JS parser = the streaming unzip issue. How can we solve it? via node-js with embedded C code?

**Comment by HadrienGardeur** [comment]
I fail to see the value of "modeling" in TypeScript something that will be written after in Swift or Java (each language have its specifities and a parser is IMO not complex enough to require this phase anyway). 

This is far from my definition of being agile: starting with the least useful implementation of it all. I strongly object against this idea.

If we want a "Typescript playground", this can be any other module for which we're far more likely to require JS.

**Comment by clebeaupin** [comment]
@HadrienGardeur What type of language do you suggest for interface modeling ?

**Comment by danielweck** [comment]
Re. "a parser is IMO not complex enough to require this phase anyway":
the proposed starting point is publication fetcher + content preprocessor + parser / internal data model.
The existing implementations in ReadiumSDK (C++) and ReadiumJS (readium-js + readium-shared-js) are not trivial, especially as Readium aims to be a reference implementation of the EPUB standard(s), not a narrow-focused feature/product -driven software. It would be beneficial to cleanup the APIs and implement proper automated regression testing. Then, to build upon this more robust foundation, as we refactor the layout + rendering engine (which is a pain point highlighted by all Readium adopters).

That being said, if a vendor has a business focus on iOS and/or Android, then the functional scope can be reduced to HTTP server + filesystem access to zipped or exploded EPUBs. It's a different story in web apps and hybrid apps, where there are multiple ways to implement this.

Based on what I've heard from various stakeholders during the conference calls, and in the survey report, there is not a complete alignment / agreement yet with regards to targeted technologies and platforms (there are several declinations of "mobile", and only EDRLab seems to prioritise desktop). I don't think there will be a unilateral approach. As Laurent argued in another discussion thread, a TypeScript-defined API would offer resistance-free R&D / prototype iterations for Electron (and any other JavaScript platform). I hope that vendors who wish to replace the ReadiumSDK C++ codebase ; partly or wholely ; with Java or Swift, would be able to contribute developer time. Obviously, there would be tight cross-collaboration.

Let's remember that most pressing issues / bugs are in readium-shared-js (i.e. the layout and rendering engine). That's the short-term maintenance Readium-1 goals sorted. Readium-2 has a much longer-term vision. So the proposal is to start with a less-ambitious, palatable software re-architecture + development "pilot" project (the aforementioned "parser" stuff), and if the outcome is positive, then we have a strong case for adopting the same strategy when refactoring Readium-1's layout and rendering engine (which is an order of magnitude more complex than the core publication "fetcher processor parser").

**Comment by llemeurfr** [comment]
And if there is an argument loop for such a simplified scope, we can fear the next steps.

**Comment by HadrienGardeur** [comment]
> the proposed starting point is publication fetcher + content preprocessor + parser / internal data model

Could you provide a better breakdown of what will be handled by each of these parts @danielweck ?
I just want to make sure that I understand this completely and that I'm not missing anything.
