### ISSUE TITLE
Handling fallbacks

### ISSUE THREAD

**Issue by HadrienGardeur** [readium/readium-2#24]
Both EPUB 2.x and EPUB 3.x support fallbacks for formats that are not core formats (XHTML + SVG in EPUB 3.x, but also DTBook in EPUB 2.x).

Since we're targeting browser engines with Readium 2, it seems very unnecessary to follow the same behavior.

Here's my proposal regarding fallbacks:

- the `spine` should directly reference the fallback for all unknown media types, without any equivalent to the `fallback` attribute
- for audio/video/image formats that are supported in browser engines, we could reference these resources directly instead of the HTML fallback, or include a `fallback` property in `properties`

This means that the streamer won't support DTBook-only EPUB 2.x, but I believe that's a reasonable enough compromise.

cc @danielweck @rkwright thoughts?

**Comment by rkwright** [comment]
@HadrienGardeur: can you give an example of what you mean for the second case?  It's not clear to me how this would work.  I assume you are suggesting this behaviour/representation would be in the JSON manifest built from a valid EPUB 2/3.x package as this behaviour is specifically disallowed in the EPUB spec.

**Comment by HadrienGardeur** [comment]
Yes, I've seen comics that for example use a JPEG/PNG that fallbacks to HTML.

In the JSON manifest, they could simply use the following object in the spine:
```json
{
  "href": "page1.png",
  "type": "image/png",
  "properties": {"fallback": "page1.html"}
}
```

**Comment by rkwright** [comment]
@HadrienGardeur OK.  That makes sense to me.  Much cleaner than the way it is done in the spec.  I had to create an EPUB recently that had fallbacks (for images in a children's book) but it was so painful I gave up and wrapped all the images in a trivial HTML instead.  The worst aspect was that you are not allowed to use the same HTML fallback for all the different images - you have to have a separate one for each image or EPUBCheck emits errors.

**Comment by HadrienGardeur** [comment]
@rkwright in this example we would reference the unique HTML fallback, but we could also support other formats such as CBZ/CBR and generate an HTML fallback for those to make them compatible with R2 apps.

**Comment by HadrienGardeur** [comment]
Based on recent discussions during the weekly Readium-2 call, fallbacks are now considered out of scope for the first iterations of this project.
