### ISSUE TITLE
Implement Media Overlay support

### ISSUE THREAD

**Issue by HadrienGardeur** [readium/readium-2#25]
The streamer is responsible for:

- parsing the OPF and SMIL files
- storing the media overlay info in-memory
- exposing the media overlay info using HTTP & JSON (document for [the syntax](https://github.com/readium/readium-2/blob/master/media-overlay/syntax.md) and for [the manifest](https://github.com/readium/readium-2/blob/master/media-overlay/README.md))

The Go version has started the implementation with the following ideas:

- whenever a spine item references a media overlay, we include a link to the media overlay service
- each SMIL file is parsed and the relevant nodes are associated to link objects in `spine`/`resources` using [a single structure](https://github.com/readium/r2-streamer-go/blob/master/models/media-overlay.go)

This issue is meant to be an epic for all on-going development in Go/Swift/Java for this feature.

**Comment by danielweck** [comment]
The NodeJS implementation has the same level of support compared with Go, but fixes the SMIL data model (interspersed par/seq). I will file a separate issue.
https://github.com/edrlab/r2-streamer-js
