### ISSUE TITLE
Parse table of contents in the streamer

### ISSUE THREAD

**Issue by HadrienGardeur** [readium/readium-2#29]
This is a meta issue to cover all TOC related issues in the streamer.

In EPUB 2.x and 3.x this means parsing:

- NCX
- Navigation Document
- Landmarks in the OPF

Spec document for the Readium Web Publication Manifest is still a work in progress and will be referenced here.

Go version already supports a large chunk of this.

**Comment by danielweck** [comment]
The NodeJS implementation is on par with Go.
https://github.com/edrlab/r2-streamer-js
