### ISSUE TITLE
Project-wide board for epics/action items

### ISSUE THREAD

**Issue by HadrienGardeur** [readium/readium-2#31]
As I mentioned before in another issue and on the latest weekly call, in an effort to be as transparent as possible, there's now a project board for Readium-2 at https://github.com/orgs/readium/projects/1

Project board are a relatively new feature on Github, and they can either be associated to:

- an organization
- or a repo

When a board is associated to an organization, you can reference issues from any repo in there but you need to be a member of that organization to view the board (which limits its potential in terms of visibility and transparency).

When a board is associated to a repo, all you need is read access to the repo to see it.

I wasn't aware of the requirement regarding membership for organization-wide board, and being able to reference cross-repo issues sounded like a useful feature.

Should we revisit that decision and use a repo-level board instead? As long as we keep all epics on this repo, it should work too.

cc @aslagle @rkwright @danielweck @llemeurfr

**Comment by danielweck** [comment]
Visibility of the cross-repository "project board" to the general public (i.e. not just to `readium` organisation members) certainly appears to be a determining factor.
I get HTTP 404 Not Found when navigating to https://github.com/orgs/readium/projects/1 when I am not logged into GitHub. Not good.

**Comment by HadrienGardeur** [comment]
Yeah I fully agree that the whole 404 thing is a big issue for such a board.

**Comment by HadrienGardeur** [comment]
I've replaced the organization board by a project board at https://github.com/readium/readium-2/projects/1
