### ISSUE TITLE
Replace the term page and synthetic page

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-2#45]
Synthetic page is an Adobe creation, cryptic. 
We should find an alternative for 
Page (the text fragment/segment between two synthetic breaks) 
Page number (0 or 1 based?)
The current position, expressed as a percentage, in the publication.

**Comment by llemeurfr** [comment]
A few proposals:

- Fragment or Region or Box -> replaces the terme Page (CSS fragmentation module -> fragmentation container).
- Index or Position -> replaces the term Page Number.
- Percentage -> position expressed as a percentage, in the publication.

**Comment by HadrienGardeur** [comment]
Right now we're using:

- "page" for the equivalent of Adobe's creation
- "position" to provide an overall progression in % (expressed as a float between 0 and 1)

I agree that page can be confusing and would love to see a better term for it, but I haven't seen convincing proposals IMO so far.

Any other ideas?

**Comment by llemeurfr** [comment]
I have discussed this with Alexandre yesterday, and we settled internally on:
- "region" for the synthetic page, as it implicitly conveys the concept of rectangle screen region;
- "index" for the notion of page number, as it is indeed an index referencing individual regions.  

For an overall progression in %, I would favor the term "progression".

**Comment by danielweck** [comment]
I think we also need to clarify the terms "references" and "locators".

**Comment by danielweck** [comment]
I like "progression" better than "position" (% [0 ... 1]).

**Comment by danielweck** [comment]
The term "region" is overused (e.g. Regions Of Interest in EPUB3 Adaptive Layout).
Plus, I don't think we should attempt to define document fragments as contiguous "ranges of content", but instead as an ordered sequence of "breaks" (i.e. boundaries, such as EPUB3 `epub:type="pagelist"` and `epub:type="page-break"`). This way, a navigation hyperlink to a given "break" actually re-positions the reader at the beginning of the desired stream of content to read (unlike printed page numbers which are traditionally located at the bottom / after the range of content corresponding to that page).

**Comment by llemeurfr** [comment]
Not sure I understand. In reflow mode, the CSS columns trick produces "ranges of content" that appear on the screen, and we tend to call that a "page", with is really overused because the page-breaks also define "page" separators. The "region" proposal is a simple alternative to this false "page". Do you think we should not define any term for this? we name it every day ...

**Comment by HadrienGardeur** [comment]
I also find region overused and confusing with both Regions of Interest (EPUB) and CSS Regions.

I'm not quite convinced about index either, it has the potential to be as confusing as page.

If we rename "position" into "progression", could we use "position" instead of "page"?

**Comment by danielweck** [comment]
Bearing in mind, I am not talking about end-user terminology, but naming conventions for low-level data / properties generated by the "arbitrary content fragmentor" (aka "paginator" service) which produces a sequence of "breaks" (atomic precise locations within the primary linear reading flow). The concept of "range of content" can be extrapolated if needed, for example to determine whether a particular HTML fragment (image, div, etc.) is fully or partially contained between two consecutive break boundaries.

**Comment by danielweck** [comment]
I too prefer position instead of page or index.

**Comment by llemeurfr** [comment]
If the context is not the display level but the lower paginator level,  I'm ok with **position** for expressing this kind of separator between fragments and **progression** for expressing a %.

**Comment by HadrienGardeur** [comment]
Great, this issue is now resolved.
