### ISSUE TITLE
Should there be a desktop version of Readium-2?

### ISSUE THREAD

**Issue by rkwright** [readium/readium-2#5]
#### This is a discussion
- Should there be a desktop version?
- If so, should it be native, like today?  
- Or only a hybrid version?
- Does it need to support DRM?

**Comment by llemeurfr** [comment]
Definitely yes, and it should be an hybrid version (Windows/Mac/Linux). 
The existence of a Readium desktop application targeting accessibility and content protection will be a very useful thing for both public library patrons and print-disabled people (using a screen reader). 
The EDRLab Electron prototype works pretty well, it embeds the Readium SDK and Readium LCP,  we'll finalize it after the LCP developments are done.

**Comment by dauwhe** [comment]
As a publisher, we also have urgent need of a desktop reading system for proofreading, etc.

**Comment by johanpoirier** [comment]
CloudReader + [Electron](http://electron.atom.io/) = Desktop client

**Comment by llemeurfr** [comment]
> CloudReader + Electron = Desktop client
Well CloudReader + optimum Zip handling + DRM support + Electron = Desktop client 
so CloudReader + Readium SDK (current) + Electron = Desktop client

**Comment by rkwright** [comment]
@llemeurfr Well, one key question is DRM required on the desktop?  At this point, I don't know of anyone asking for it. For proofreading I don't think it is needed. So what is the use case where a desktop reader with DRM is needed? I'm not saying there isn't one, only that I am not aware of one.

**Comment by dauwhe** [comment]
Surprising numbers of people read ebooks on computers, at least in 2012.

http://libraries.pewinternet.org/2012/04/04/the-rise-of-e-reading/

> * 42% of readers of e-books in the past 12 months said they consume their books on a computer
> * 41% of readers of e-books consume their books on an e-book reader like original Kindles or Nooks
> * 29% of readers of e-books consume their books on their cell phones
> * 23% of readers of e-books consume their books on a tablet computer.

**Comment by johanpoirier** [comment]
> Well, one key question is DRM required on the desktop?

Why wouldn't it be? People reading with ADE will be pleased to get rid of it and read LCP books with their readium desktop reader.

**Comment by llemeurfr** [comment]
@rkwright,well, DRM support is not useful for proofreading, but it is for public libraries (for me this is the main use case, managing rental time) and it is required by publishers for any end-user RS. Public libraries provide RS on their site, on PCs, so they need a DRM support. Print disabled people need screen readers, so they use PCs, and they want to be able to access natively accessible EPUB. These will also protected by a DRM (accessible-friendly).
