### ISSUE TITLE
What's the status of Readium-2 SDK for Web?

### ISSUE THREAD

**Issue by hz0324** [readium/readium-2#58]
We have been using Readium-1 building a web app. Now we think it is the time to rewrite our app.
So we wondered is the Readium-2 for Web ready to use now? If not, when will it be ready? Thanks.

FYI, I have read the README, but not very clear about this question.
Please help, Thanks.

**Comment by danielweck** [comment]
As far as I know, nobody is working on a Readium-2 "web / cloud reader" at this point in time. The primary development focus is on desktop (Linux, Windows, Mac) and mobile apps (Android, iOS).

I think there are people interested in combining the Readium-2 "streamer" (content server) with the Readium-1 "navigator" (reader interface), but I am not sure about current status.

**Comment by hz0324** [comment]
@danielweck Thank you very much, Daniel. 

BTW, is it possible to Parse the epub file in server side and render the book on client side, such as Browser?

I read the README, thought this might be possible using Readium-2 project. But can not find a working demo now.

**Comment by danielweck** [comment]
Native Readium-2 desktop / mobile "app" implementations instantiate the "streamer" (content parser + server) inside the client-side runtime (alongside the "navigator" component). So even though such apps are designed to work offline, under the hood there is a regular HTTP architecture that is applicable to network / internet deployments as well.

For instance, the NodeJS / TypeScript implementation of Readium-2 provides an Express-based "streamer" service that can be deployed online purely to parse + serve EPUB contents (no built-in reader / viewer interface). As a matter of fact, `r2-streamer-js` builds are automatically uploaded (continuous integration from the `develop` branch https://github.com/edrlab/r2-streamer-js/tree/develop ) to:
https://readium2.herokuapp.com

If you try the built-in publication, you will see that basic reader links are provided (for testing, not production-ready)

Note that the last link down the page points to an experimental Readium-1 implementation (web / cloud reader) that supports the "webpub manifest" JSON format natively. This is effectively a bridge between Readium2 - Readium2. Unfortunately there are bugs in the metadata parser, so currently the links fail (contributions welcome)
See:
https://github.com/evidentpoint/readium-js/commit/e3d75b6a2945f31910043fff954156900586903b#r22835106
and:
https://github.com/readium/readium-js/pull/180
The most current branch is:
https://github.com/readium/readium-js/commits/feature/readium2-evidentpoint
...which derives:
https://github.com/evidentpoint/readium-js/commits/feature/readium2
CC @JCCR @barbender @evidentpoint

**Comment by HadrienGardeur** [comment]
> BTW, is it possible to Parse the epub file in server side and render the book on client side, such as Browser?

This is completely possible. You could either deploy the JS or Go streamer on the server side and build/use whatever you want for the rendering on the client side.

In addition to the Readium-1 bridge, I know that @fchasen is working on making EPUB.js compatible for example and you could also re-use the work that NYPL did as well (ping @aslagle).
Building your own solution is possible too and would require less efforts IMO than with Readium-1 once Readium CSS is injected properly by the streamer.

**Comment by danielweck** [comment]
Thanks Hadrien for the additional information. As a matter of fact, both EPUBjs and NYPL reader prototypes are linked from the r2-streamer-js deployment I mentioned. The NYPL app that's shipped there may be a little out of date, but you'll get the idea.

**Comment by hz0324** [comment]
Thank you guys. I am going to play with them now. ^_^
