### ISSUE TITLE
How to set bookmarks

### ISSUE THREAD

**Issue by AlexZeitler** [readium/readium-2#59]
Hi,

how do I set bookmarks using Readium Chrome app?

**Comment by llemeurfr** [comment]
Sorry, you're in the wrong project. readium-2 is the new codebase, the readium chrome app does not belong to this project.   
But to answer to your question, Readium is an open-source volunteer effort and nobody has volunteered to add bookmarks to the Readium Chrome app. As Google will deprecate all Chrome apps in 2018, the EDRLab is working on a new app called Readium Desktop. This app will have bookmarks in the coming months.
