### ISSUE TITLE
How should versioning be implemented in Readium-2?

### ISSUE THREAD

**Issue by rkwright** [readium/readium-2#6]
#### This is a Discussion
- How should versioning be implemented?
- Part of the build process?
- Part of source-code control process?
- Does it need to vary across platforms?

**Comment by llemeurfr** [comment]
I would propose to use a simple versioning scheme, beginning with "2.0 alpha x" versions, "2.0" as soon as we have an MVP (mini viable product), the use the usual max.min-2-digits versioning scheme. 
It should be the same for all platforms, and used as github tags.

**Comment by rkwright** [comment]
@llemeurfr  That sounds reasonable.  But there are a bunch of wrinkles here.  Let’s explore some of them:

1. The first wrinkle is that the Chrome Extension (which is actually a packaged app) is already 2.x. But that's probably moot since we need to replace it anyway.  So we can put that one aside.
2. The second wrinkle is how many versions do we have?  There is the semantic versioning approach (like you propose) with major.minor.patch format.  However, I believe we need to also provide github versioning, as the current Chrome Extension (and CloudReader) do.  This provides a clear link to what code in our github was used to generate some code.  So how do we tie the semantic versioning to “github versioning” in a clear and robust way?  One possibility is that the “patch” field of the version IS the github hash, e.g. 2.1.ffecd87
3. The third wrinkle is then which hash?  At present, we have four major components in ReadiumJS (for example): readium-js, readium-js-viewer, readium-shared-js and readium-cfi-js.  Since they are in different repos there have different github hashes for each one.  I am hopeful that we can move to a single repo for readium-2, but with per-platform development that may not be feasible or desirable. But we can at least strive to have each “stack” (iOS/Android/hybrid, for example) be in a separate repo. Still a bit confusing but perhaps workable. But the net net is that each "stack" would have a different "patch" version.
4. Next, I think we are in agreement that we have to have strict control and adherence to an API “contract”.  So how is that enforced?  If we have per-platform development, then the interfaces will be somewhat different, even if we have the “master” interface specified in neutral IDL.  How does versioning for that work?  Are there 3 (or four) different versions?  How is adherence to the contract enforced?
5. Finally, what about third-party libraries? Do we expose their versions?  What about variants across platforms?  With Adobe RMSDK, we reported (via an API of sorts) the versions of all the third-party libraries that we required, but RMSDK was much simpler in several ways than readium-2 will be.  RMSDK required only a few libraries, which had to be linked in by the app developers, we didn’t supply them. And we only officially supported OSX and Windows with Linux for internal testing.  Reporting third party libraries was extremely helpful in product support though because we DIDN'T know what libraries the app developers might be using.

**Comment by danielweck** [comment]
Semver is the way to go.
http://semver.org
Readium-2 modules will probably be published at NPM, so a reliable / consistent versioning strategy for all intermediate stages is needed (alpha, beta, RC, stable).
https://semver.npmjs.com

**Comment by danielweck** [comment]
Reminder: Readium-1 versioning is a reconciliation attempt of semver (human-readable version strings) and low-level Git commit hash tracking (for each repository / submodule).
Once a proper semver-driven versioning process is in place, there is no need for the added Git complexity.

**Comment by rkwright** [comment]
@danielweck  Right, but if I have version 2.1.2 of Readium-2 for Android, how do I know where that is in the chain of commits?  By the github tag, I suppose? In that case, "proper" needs to explicitly include the release process including such tagging.

**Comment by danielweck** [comment]
Yes, a semver string must be encoded somewhere in the application build (or within each of the application's components, assuming Readium software modules are designed for reuse in other application contexts), typically in package.json for NPM. Corresponding release tags must be recorded in the GitHub repositories, so that an accurate point in the source code history can be matched with software builds.
One other important aspect ; which Readium-1 is not dealing with correctly yet ; is that a record of the exact version numbers of NPM dependencies must be recorded alongside the release tag, typically in a shrinkwrapped package.json (Note that I am putting emphasis on NPM here to illustrate the points, but this could be any other package management platform)

**Comment by llemeurfr** [comment]
re 2.  the github correspondance can be provided via tags. https://github.com/Microsoft/vscode and https://github.com/electron/electron/commits/master show good examples of a tagging strategy, I think (links provided by Cyrille).

re 3. versioning per platform (iOS, Web etc.). The semantic versioning can be copied to the different repos, with the tagging strategy introduced above (same semver at different commit points). I agree that the patch number will be different for each platform (difference in debug state), but it's not problematic, as it's the major.minor version that indicates functionalities.

re 4. the major.minor version indicate adherence to a "master" API version. There may be "custom" API details which differ btw platforms, which is acceptable if they are carefully documented in the platform project.

re 5. about third-party libraries, Cyrille showed me a very good example in https://github.com/Microsoft/vscode, with a "third-parties" text document that seems created on the fly by the build/packaging system. If we can copy the script, do you think we have a solution?

Also, an interesting reference about semantic versioning, strict adherence to an API and dependency hell: http://semver.org/ -> should we reference it for our use ? (for us I think item 10 is of no use, see 2. above)

**Comment by danielweck** [comment]
@llemeurfr yes, Readium-1 (ReadiumJS) already makes use of release tags:
https://github.com/readium/readium-js-viewer/releases
But because nothing gets published to the NPM registry (or any other package manager), the semver increment policy is not critical (whereas it would be in Readium-2).

**Comment by danielweck** [comment]
@llemeurfr re. "third party libs": sure, you can derive / produce human-readable documents from a shrinkwrapped set of NPM dependencies. See https://docs.npmjs.com/cli/shrinkwrap
(PS: I realize I am putting a lot of emphasis on NPM, but please bear in mind that this is for illustration purposes only)
